global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:50051']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s